CREATE TABLE IF NOT EXISTS `message` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(50) NOT NULL COMMENT '留言者昵称',
  email VARCHAR(100) COMMENT '邮箱',
  website VARCHAR(200) COMMENT '网站',
  content TEXT NOT NULL COMMENT '留言内容',
  parent_id BIGINT DEFAULT 0 COMMENT '父留言ID',
  reply TEXT COMMENT '博主回复',
  avatar VARCHAR(500) COMMENT '头像URL',
  ip_address VARCHAR(50) COMMENT 'IP地址',
  is_show INT DEFAULT 1 COMMENT '1=显示 0=隐藏',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留言板';
